### ISSUE TITLE
Add an About screen, accessible from hamburger menu

### ISSUE THREAD

**Issue by jasonccox** [CellWatch/cellwatch-app#43]
Include information about the orgs involved in development. Mention Rockefeller. Include contact info.

Requested by Grace.

**Comment by jasonccox** [comment]
Let's replace the help entry in the hamburger menu with an about entry. (We can add help back later once we get it implemented. This should be a good icon: https://fontawesome.com/icons/circle-info?f=classic&s=solid (just add it as a vector asset).

We can use the below text for now.

---

The CellWatch app is part of the CellWatch open-source cellular network measurement suite created by researchers at the Georgia Institute of Technology; the University of California, Santa Barbara; and Northern Arizona University. CellWatch is generously funded by the Rockefeller Foundation.

Learn more at our website: [sites.gatech.edu/cellwatch](https://site.gatech.edu/cellwatch).

CellWatch is built with many open source libraries. Their licenses and copyright notices are included below.

[required attribution goes here]

**Comment by david-peeler** [comment]
Closed with commit 15a94a2
