### ISSUE TITLE
Improve UI appearance on various screen sizes

### ISSUE THREAD

**Issue by jasonccox** [CellWatch/cellwatch-app#46]
Specifically check for small phone screens and large tablet screens. Making the padding around the edges of each screen adjust based on the screen size may be sufficient.

Requested by Grace.

**Comment by david-peeler** [comment]
Most Recent UI Fixes:

Map Search UI Fixes: 237df85
Fixing Theming Issues: 5b3e592
Map SearchResultsView fixes: bb565d4
BottomSheet UX fixes: 5967053
Location Puck fixes: e73deaf
