### ISSUE TITLE
Inserted Measurements/Data to Suprabase is larger than an int can handle

### ISSUE THREAD

**Issue by david-peeler** [CellWatch/cellwatch-app#86]
## Steps to reproduce

Some specific measurements have numbers (unsure what column) larger than the scope of an int number (-2,147,483,647 to 2,147,483,647).

## Details

- App version: App version:1.0.0-beta.1 (6)
- Device ID: b11368cb-2c5e-44bb-8a82-928b806814df
- Date/time: Looks like multiple issues like this on Crashlytics - this one is from Sept 24, 2024 @ 9:32pm

## More info

Non-fatal Exception: io.github.jan.supabase.exceptions.BadRequestRestException
value "5572083734" is out of range for type integer URL: https://xepxxvpbexkyxrwtrgqv.supabase.co/rest/v1/rpc/insert_measurement Headers: [Authorization=[Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlcHh4dnBiZXhreXhyd3RyZ3F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzc3NjgwOTgsImV4cCI6MTk5MzM0NDA5OH0.4yPsO_M4VPJu_wt4EVcOa3Y2_paj2I_1IRKujmIVjdA], Prefer=[], apikey=[eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlcHh4dnBiZXhreXhyd3RyZ3F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzc3NjgwOTgsImV4cCI6MTk5MzM0NDA5OH0.4yPsO_M4VPJu_wt4EVcOa3Y2_paj2I_1IRKujmIVjdA], X-Device-ID=[b11368cb-2c5e-44bb-8a82-928b806814df], X-Device-Secret=[UQyyWGmZSxQ1lut4+MI9yiP2Y+1wHLmdfHOJWrM+kUQ=], Accept=[application/json], Accept-Charset=[UTF-8]] Http Method: POST

**Comment by jasonccox** [comment]
Fixed by changing basically all `integer` columns to be of type `numeric`, which permits much larger values.
